[package]
name = "prose-app-web"
version = "0.0.0"
description = "Prose Web application (Tauri packaging)"
authors = ["Prose Foundation <dev@prose.org>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-start-dragging", "shell-open", "notification-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "5.0.1"
path_trav = "2.0.0"
reqwest = { version = "0.11.25", features = ["blocking"] }
tokio = { version = "1.36.0", features = ["full"] }
thiserror = "1.0.58"
cocoa = "0.25.0"
objc = "0.2.7"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "s"
lto = true
strip = true
