[package]
name = "prose-app-web"
version = "0.0.0"
description = "Prose Web application (Tauri bundle)"
authors = ["Prose Foundation <dev@prose.org>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-center", "window-set-size", "window-set-resizable", "macos-private-api", "updater", "window-set-fullscreen", "window-start-dragging", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "5.0.1"
reqwest = "0.11.25"
tokio = { version = "1.36.0", features = ["full"] }
thiserror = "1.0.58"
cocoa = "0.25.0"
objc = "0.2.7"
percent-encoding = "2.3.1"
tauri-plugin-deep-link = "0.1.2"
window-vibrancy = "0.4.3"
notifications = { git = "https://github.com/dscso/mac-notifications.git", rev = "665766b49245ee7b94310eb6714cc5f823c7cbd2" }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = "s"
lto = true
strip = true
