on: [push]

name: Build and Release

jobs:
  ship:
    environment: build-ship
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            env/nginx/
            Dockerfile

      - name: Acquire Docker image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            proseim/prose-app-web
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=0.5.3
            type=raw,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          name: 0.5.3 Release
          workflow: build.yml
          search_artifacts: true

      - name: Extract build artifacts
        run: tar -xzvf ./release-0.5.3.tar.gz

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
