on: [push]

permissions:
  actions: read

name: Bundle and Publish

jobs:
  publish-version:
    environment: bundle-publish
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: macos
            system: mac
            architecture: aarch64
            format: dmg
          - platform: macos
            system: mac
            architecture: x86_64
            format: dmg

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 0.6.0 Bundle (${{ matrix.settings.system }}-${{ matrix.settings.architecture }})
          run-id: 13592522684
          github-token: ${{ github.token }}

      - name: Extract build artifacts
        run: tar -xzvf ./bundle-0.6.0-${{ matrix.settings.system }}.tar.gz

      - name: Publish application version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 cp --endpoint-url ${{ vars.S3_ENDPOINT }} --checksum-algorithm sha256 ${{ matrix.settings.format }}/ s3://${{ vars.S3_BUCKET }}/versions/0.6.0/${{ matrix.settings.platform }}/${{ matrix.settings.architecture }}/ --recursive --exclude "*" --include "*.${{ matrix.settings.format }}" --exclude ".*"

      - name: Publish update archive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 cp --endpoint-url ${{ vars.S3_ENDPOINT }} --checksum-algorithm sha256 ${{ matrix.settings.platform }}/ s3://${{ vars.S3_BUCKET }}/versions/0.6.0/${{ matrix.settings.platform }}/${{ matrix.settings.architecture }}/update/ --recursive --exclude "*" --include "*.tar.gz" --include "*.tar.gz.sig"

  publish-manifest:
    needs: publish-version
    environment: bundle-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src-tauri/scripts/updater.sh

      - name: Generate update manifest
        run: |
          ./src-tauri/scripts/updater.sh --endpoint=${{ vars.S3_ENDPOINT }} --bucket=${{ vars.S3_BUCKET }} --version=0.6.0 --manifest=manifest.json

      - name: Publish update manifest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 cp --endpoint-url ${{ vars.S3_ENDPOINT }} --checksum-algorithm sha256 manifest.json s3://${{ vars.S3_BUCKET }}/updates/latest.json
