on: [push, pull_request]

name: Test and Lint

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        settings:
          - platform: macos
            paths:
              - installer: ./dmg
                updater: ./macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify matrix
        run: echo "platform=${{ matrix.settings.platform }}, pathinstaller=${{ matrix.settings.paths.installer }}, pathupdater=${{ matrix.settings.paths.updater }}"
