on: [push]
name: Test on Windows

jobs:
  bundle:
    environment: bundle-build
    runs-on: ${{ matrix.settings.runner }}

    strategy:
      fail-fast: false
      matrix:
        settings:
          - runner: windows-2025
            system: windows
            architecture: x86_64
            target: x86_64-pc-windows-msvc
            bundles: msi

    outputs:
      tag: ${{ steps.current_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Verify versions
        run: node --version && npm --version && node -p process.versions.v8 && node -p process.arch

      - name: Cache build context (NodeJS)
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ runner.arch }}-node

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0

      - name: Install dependencies
        run: npm install --no-audit

      - name: Run build
        run: npm run build

      - name: Archive output files
        shell: bash
        run: tar -zcvf ./release-${{ steps.current_tag.outputs.tag }}.tar.gz dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.current_tag.outputs.tag }} Release
          path: ./release-${{ steps.current_tag.outputs.tag }}.tar.gz
          retention-days: 1
